server:
  port: 8000
  servlet:
    context-path: /demo

spring:
  resources:
    static-locations: classpath:templates/,classpath:static/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
